services:
    nginx:
        container_name: nginx
        build: nginx/
        ports:
            - "80:80"
            - "443:443"
        volumes:
          - ssl:/etc/ssl
        env_file: .env
    api:
        container_name: api
        build: api/
        env_file: .env
    rex:
        container_name: rex
        build: rex/
        env_file: .env
    www:
        container_name: www
        build: www/
        env_file: .env

volumes:
    ssl:
        name: ssl
        driver: local
        driver_opts:
            type: none
            device: ${PWD}/ssl
            o: bind
