name: Docker Compose

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: docker compose
      working-directory: /home/pi/Server
      run: docker compose up --build -d
